# Generated by Django 4.1.3 on 2022-11-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_remove_password_table_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="password_table",
            old_name="link",
            new_name="user",
        ),
    ]
