# Generated by Django 4.1.3 on 2022-11-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_rename_link_password_table_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="password_table",
            old_name="user",
            new_name="link",
        ),
    ]
