# Generated by Django 4.1.3 on 2022-11-21 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_rename_user_password_table_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="password_table",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
