# Generated by Django 4.1.3 on 2022-11-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_alter_password_table_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Password_Table",
        ),
    ]
